[package]
name = "tx_status"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.8.5"
snforge_std = { path = "../../../snforge_std" }
sncast_std = { path = "../../../sncast_std" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
