name: "Devnet Setup"

inputs:
  devnet_sha:
    description: "Commit SHA for the starknet-devnet-rs repository"
    required: true


runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: dtolnay/rust-toolchain@dc6353516c68da0f06325f42ad880f76a5e77ec9
      with:
        toolchain: 1.83.0

    - name: Cache devnet build
      id: cache-devnet
      uses: actions/cache@v4
      with:
        path: starknet-devnet-rs/target/release
        key: ${{ runner.os }}-starknet-devnet-rs-target-release-${{ inputs.devnet_sha }}

    - name: Build and install devnet
      shell: bash
      run: |
        DEVNET_INSTALL_DIR="$(git rev-parse --show-toplevel)/crates/sncast/tests/utils/devnet"
        mkdir -p "$DEVNET_INSTALL_DIR"

        if [[ ! -d starknet-devnet-rs/target/release ]]; then
          cd starknet-devnet-rs
          cargo build --release
          cp ./target/release/starknet-devnet "$DEVNET_INSTALL_DIR"
        else
          echo "Found existing starknet-devnet-rs build, skipping compilation."
          cp starknet-devnet-rs/target/release/starknet-devnet "$DEVNET_INSTALL_DIR"
        fi

    - name: Verify devnet installation
      shell: bash
      run: |
        DEVNET_INSTALL_DIR="$(git rev-parse --show-toplevel)/crates/sncast/tests/utils/devnet"
        if [[ -x "$DEVNET_INSTALL_DIR/starknet-devnet" ]]; then
          echo "starknet-devnet successfully installed at $DEVNET_INSTALL_DIR"
        else
          echo "starknet-devnet installation failed!" && exit 1
        fi

