version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: cairo-*
    groups:
      cargo-weekly:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      ci-weekly:
        patterns:
          - '*'
