[package]
name = "hello_sncast"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.7.0"
sncast_std = { path = "../../../sncast_std" }

[dev-dependencies]
snforge_std = { path = "../../../snforge_std" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
