use crate::collecting::CompiledTestCrateRaw;
use anyhow::Result;
use camino::Utf8Path;

/// Load test artifacts (deserialized compiled test crates) generated by `scarb snforge-test-collector`
pub fn load_test_artifacts(
    snforge_target_dir_path: &Utf8Path,
    package_name: &str,
) -> Result<Vec<CompiledTestCrateRaw>> {
    let snforge_test_artifact_path =
        snforge_target_dir_path.join(format!("{package_name}.snforge_sierra.json"));
    let test_crates = serde_json::from_str::<Vec<CompiledTestCrateRaw>>(&std::fs::read_to_string(
        snforge_test_artifact_path,
    )?)?;
    Ok(test_crates)
}
