[package]
name = "parametrized_testing_fuzzer"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.12.0"
assert_macros = "2.12.0"

[dev-dependencies]
snforge_std = { path = "../../../snforge_std" }

[scripts]
test = "snforge test"
