[alias]
lint = "clippy --all-targets --all-features -- --no-deps -W clippy::pedantic -A clippy::missing_errors_doc -A clippy::missing_panics_doc -A clippy::default_trait_access"
"test e2e" = "test --test main e2e"
"test integration" = "test --test main integration"
