[package]
name = "addition"
version.workspace = true
edition = "2024_07"

[dependencies]
starknet = "2.8.5"

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true

[lib]
