name: My workflow
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
      - name: Check versions
        run: |
          snforge --version
          sncast --version
