name: My workflow
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Starknet Foundry
        id: setup-snfoundry
        uses: foundry-rs/setup-snfoundry@v3
      - name: Check versions
        run: |
          snforge --version
          sncast --version
      - name: Cache Starknet Foundry installation
        uses: actions/cache@v3
        with:
          path: ${{ steps.setup-snfoundry.outputs.starknet-foundry-prefix }}
          key: ${{ runner.os }}-snfoundry-${{ steps.setup-snfoundry.outputs.starknet-foundry-version }}