[package]
name = "conditional_compilation"
version = "0.1.0"
edition = "2023_11"

[features]
default = ["enable_for_tests"]
enable_for_tests = []

[dependencies]
starknet.workspace = true
snforge_std.workspace = true
assert_macros.workspace = true

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
