name: Bug Report
description: Report a bug
labels: [ "bug" ]
body:
  - type: dropdown
    id: tool-name
    attributes:
      label: Which component is your bug related to?
      multiple: true
      options:
        - snforge
        - sncast
    validations:
      required: true

  - type: input
    id: foundry-version
    attributes:
      label: Foundry Version
      description: What Foundry version are you using?
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system are you using?
      multiple: false
      options:
        - Windows
        - Linux
        - MacOS
    validations:
      required: true

  - type: dropdown
    id: system-architecture
    attributes:
      label: What system architecture are you using?
      multiple: false
      options:
        - x86
        - arm
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: Describe the issue here.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Trace
      description: Please provide output of the error.
    validations:
      required: false

  - type: checkboxes
    id: verified-not-exists
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues and verified no issue exits for this problem.
