blank_issues_enabled: false
contact_links:
  - name: Telegram Support Channel
    url: https://t.me/starknet_foundry_support
    about: This issue tracker is only for bugs and feature requests. Support is available through Telegram channel.
