[package]
name = "full_example"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
snforge_std.workspace = true
sncast_std.workspace = true
map = { path = "../../crates/map" }

[[target.starknet-contract]]
build-external-contracts = ["map::MapContract"]

[[target.lib]]
sierra = true

[scripts]
test = "snforge test"
