mod account;
mod alias;
mod call;
mod completions;
mod config_path;
mod declare;
mod declare_from;
mod deploy;
mod devnet_accounts;
mod fee;
mod get;
mod invoke;
#[cfg(feature = "ledger-emulator")]
pub(crate) mod ledger;
mod main_tests;
mod multicall;
mod proof;
mod script;
mod selector;
mod show_config;
mod utils;
mod verify;
