disallowed-methods = [
    { path = "std::env::args", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::env::args_os", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::env::current_dir", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::env::current_exe", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::env::home_dir", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::env::var", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::env::var_os", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::env::vars", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::env::vars_os", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::fs::exists", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::fs::hard_link", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::fs::metadata", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::fs::read", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::fs::read_dir", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::fs::read_link", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::fs::read_to_string", reason = "all external inputs should be handled inside ExternalInputs struct" },
    { path = "std::fs::symlink_metadata", reason = "all external inputs should be handled inside ExternalInputs struct" },
]
