[workspace]
members = ["scripts/*"]

[workspace.dependencies]
starknet = "2.7.0"
snforge_std = { path = "../../../snforge_std" }
sncast_std = { path = "../../../sncast_std" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
