[package]
name = "declare"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.8.5"
sncast_std = { path = "../../../sncast_std" }
snforge_std = { path = "../../../snforge_std" }

[[target.starknet-contract]]
sierra = true

[[target.lib]]
sierra = true

[scripts]
test = "snforge test"
