[profile.default]
fail-fast = false
retries = 0

[test-groups]
devnet-sequential = { max-threads = 1 }
ledger = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'package(sncast) and (test(/^e2e::/) | test(/^integration::/) | test(/^docs_snippets::/) | test(/^helpers::devnet_provider::/) | test(/^helpers::devnet_detection::/))'
test-group = "devnet-sequential"

[[profile.default.overrides]]
filter = 'package(sncast) and (test(/^e2e::devnet_accounts::/) | test(/^e2e::script::init::/))'
retries = 1

[[profile.default.overrides]]
filter = 'package(sncast) and (test(/^e2e::ledger::/) | test(/^docs_snippets::ledger::/))'
test-group = "ledger"
retries = 3

[[profile.default.overrides]]
filter = 'package(sncast) and test(=e2e::devnet_accounts::use_devnet_account_with_network_flags)'
retries = { backoff = "exponential", count = 3, delay = "5s" }
