use crate::{TestCaseIsIgnored, expected_result::ExpectedTestResult};
use cheatnet::runtime_extensions::forge_config_extension::config::{
    RawAvailableResourceBoundsConfig, RawFuzzerConfig,
};
use starknet_api::block::BlockNumber;
use url::Url;

#[must_use]
pub fn sanitize_test_case_name(name: &str) -> String {
    // Test names generated by `#[test]` and `#[fuzzer]` macros contain internal suffixes
    name.replace("__snforge_internal_test_generated", "")
        .replace("__snforge_internal_fuzzer_generated", "")
}

#[derive(Debug, Clone, PartialEq)]
pub struct ResolvedForkConfig {
    pub url: Url,
    pub block_number: BlockNumber,
}

/// Test case with config that has been resolved, that is
///     `#[fork("name")]` -> url and block id
///     fetches block number
#[derive(Debug, Clone, PartialEq)]
pub struct TestCaseResolvedConfig {
    pub available_gas: Option<RawAvailableResourceBoundsConfig>,
    pub ignored: bool,
    pub expected_result: ExpectedTestResult,
    pub fork_config: Option<ResolvedForkConfig>,
    pub fuzzer_config: Option<RawFuzzerConfig>,
    pub disable_predeployed_contracts: bool,
}

impl TestCaseIsIgnored for TestCaseResolvedConfig {
    fn is_ignored(&self) -> bool {
        self.ignored
    }
}
