name: My workflow
on:
  push:
  pull_request:
env:
  STARKNET_FOUNDRY_VERSION: 0.34.0
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore Starknet Foundry installation from cache
        uses: actions/cache@v4
        id: cache-snfoundry
        with:
          path: /opt/hostedtoolcache/starknet-foundry/${{ env.STARKNET_FOUNDRY_VERSION }}/x86_64-unknown-linux-gnu
          key: snfoundry-${{ env.STARKNET_FOUNDRY_VERSION }}-x86_64-unknown-linux-gnu
      - name: Setup Starknet Foundry
        if: steps.cache-snfoundry.outputs.cache-hit != 'true'
        id: setup-snfoundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: ${{ env.STARKNET_FOUNDRY_VERSION }}
      - run: snforge
      - name: Cache Starknet Foundry
        if: steps.cache-snfoundry.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/starknet-foundry/${{ env.STARKNET_FOUNDRY_VERSION }}/x86_64-unknown-linux-gnu
          key: snfoundry-${{ env.STARKNET_FOUNDRY_VERSION }}-x86_64-unknown-linux-gnu