use cairo_lang_casm::hints::Hint;
use num_bigint::BigInt;
use serde::{Deserialize, Serialize};

pub type CasmCodeOffset = usize;
pub type CasmInstructionIdx = usize;

#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct RawCasmProgram {
    pub assembled_cairo_program: AssembledCairoProgramWithSerde,
    /// `debug_info[i]` contains the following information about the first CASM instruction that
    /// was generated by the Sierra statement with
    /// `StatementIdx(i)` (i-th index in Sierra statements vector):
    /// - code offset in the CASM bytecode
    /// - index in CASM instructions vector
    ///
    /// Those 2 values are usually not equal since the instruction sizes in CASM may vary
    pub debug_info: Vec<(CasmCodeOffset, CasmInstructionIdx)>,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct AssembledCairoProgramWithSerde {
    pub bytecode: Vec<BigInt>,
    pub hints: Vec<(usize, Vec<Hint>)>,
}
