use cairo_lang_casm::hints::Hint;
use num_bigint::BigInt;
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap};

pub type CasmCodeOffset = usize;
pub type CasmInstructionIdx = usize;

#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
pub struct RawCasmProgram {
    pub assembled_cairo_program: AssembledCairoProgram,
    /// `debug_info[i]` contains the following information about the first CASM instruction that
    /// was generated by the Sierra statement with
    /// `StatementIdx(i)` (i-th index in Sierra statements vector):
    /// - code offset in the CASM bytecode
    /// - index in CASM instructions vector
    ///
    /// Those 2 values are usually not equal since the instruction sizes in CASM may vary
    pub debug_info: Vec<(CasmCodeOffset, CasmInstructionIdx)>,
    /// Compiler-inferred costs of raw Sierra functions, keyed by their Sierra entry-point
    /// statement index.
    pub function_costs: HashMap<usize, BTreeMap<RawCostTokenType, i64>>,
}

#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone, Copy)]
#[serde(rename_all = "snake_case")]
pub enum RawCostTokenType {
    Const,
    Pedersen,
    Poseidon,
    Bitwise,
    EcOp,
    AddMod,
    MulMod,
    Blake,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct AssembledCairoProgram {
    pub bytecode: Vec<BigInt>,
    pub hints: Vec<(usize, Vec<Hint>)>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn deserializes_function_costs_keyed_by_sierra_entry_point() {
        let program = serde_json::from_value::<RawCasmProgram>(json!({
            "assembled_cairo_program": {"bytecode": [], "hints": []},
            "debug_info": [],
            "function_costs": {"42": {"const": 10, "pedersen": 2}}
        }))
        .unwrap();

        assert_eq!(
            program.function_costs[&42],
            BTreeMap::from([
                (RawCostTokenType::Const, 10),
                (RawCostTokenType::Pedersen, 2),
            ])
        );
    }
}
