name: Check benchmarks

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  benchmarks:
    name: Verify benchmarks are up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84
      - uses: software-mansion/setup-scarb@v1.3.2
      - name: Install universal-sierra-compiler
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/universal-sierra-compiler/master/scripts/install.sh | sh

      - run: cargo test --benches
