name: Check benchmarks

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  benchmarks:
    name: Verify benchmarks are up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@439cf607258077187679211f12aa6f19af4a0af7
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8
      - uses: software-mansion/setup-scarb@v1.3.2

      - run: cargo test --benches
